### ISSUE TITLE
Meet an Error in Kernel

### ISSUE THREAD

**Issue by tynus2** [sigeisler/reliable_gnn_via_robust_aggregation#1]
I used other datasets to run the code, but an error occurred:  "module 'kernels' has no attribute 'topk'" 
Could you help me to solve it? 
Many thanks.

**Comment by sigeisler** [comment]
Hi @Tendencyox could you resolve the issue? looks like the custom kernels were not installed properly. Please let me know how I can be of help or how we can improve the installation/documentation.

Thanks!
